config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :outfits
  resources :outfit_items
  resources :items
  
  root "outfits#landing"
  get "/contact", to: "contact#new", as: "new_contact"
  post "/contact", to: "contact#create"
end

app/models/outfit_item.rb
# == Schema Information
#
# Table name: outfit_items
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  item_id    :integer
#  outfit_id  :integer
#
# Indexes
#
#  index_outfit_items_on_item_id    (item_id)
#  index_outfit_items_on_outfit_id  (outfit_id)
#
class OutfitItem < ApplicationRecord
  belongs_to :outfit
  belongs_to :item, dependent: :destroy
end

app/controllers/outfit_items_controller.rb
class OutfitItemsController < ApplicationController
  before_action :set_outfit_item, only: %i[ show edit update destroy ]

  def index
    @outfit_items = OutfitItem.all
  end

  def show
  end

  def new
    @outfit_item = OutfitItem.new
  end

  def edit
  end

  def create
    @outfit_item = OutfitItem.new(outfit_item_params)

    respond_to do |format|
      if @outfit_item.save
        format.html { redirect_to outfit_item_url(@outfit_item), notice: "Outfit item was successfully created." }
        format.json { render :show, status: :created, location: @outfit_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @outfit_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @outfit_item.update(outfit_item_params)
        format.html { redirect_to outfit_item_url(@outfit_item), notice: "Outfit item was successfully updated." }
        format.json { render :show, status: :ok, location: @outfit_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @outfit_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @outfit_item.destroy

    respond_to do |format|
      format.html { redirect_to outfit_items_url, notice: "Outfit item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_outfit_item
      @outfit_item = OutfitItem.find(params[:id])
    end

    def outfit_item_params
      params.require(:outfit_item).permit(:outfit_id, :item_id)
    end
end

app/views/outfit_items/_form.html.erb
<%= form_with(model: outfit_item) do |form| %>
  <% if outfit_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(outfit_item.errors.count, "error") %> prohibited this outfit_item from being saved:</h2>

      <ul>
        <% outfit_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/outfit_items/_outfit_item.html.erb
<div id="<%= dom_id outfit_item %>">
  <p>
    <strong>Outfit:</strong>
    <%= outfit_item.outfit_id %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= outfit_item.item_id %>
  </p>

</div>

app/views/outfit_items/edit.html.erb
<h1>Editing outfit item</h1>

<%= render "form", outfit_item: @outfit_item %>

<br>

<div>
  <%= link_to "Show this outfit item", @outfit_item %> |
  <%= link_to "Back to outfit items", outfit_items_path %>
</div>

app/views/outfit_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Outfit items</h1>

<%= link_to "New outfit item", new_outfit_item_path %>

<div class="row row-cols-1 row-cols-md-2 g-4" id="outfit_items">
  <% @outfit_items.each do |outfit_item| %>
    <div class="col">
      <div class="card">
        <% if outfit_item.item.present? %>
          <img src="<%= outfit_item.item.photo_url %>" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= outfit_item.item.details %></h5>
            <%= link_to "Show this outfit item", outfit_item %>
          </div>
        <% else %>
          <div class="card-body">
            <p class="card-text">No associated item</p>
            <%= link_to "Show this outfit item", outfit_item %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/outfit_items/new.html.erb
<h1>New outfit item</h1>

<%= render "form", outfit_item: @outfit_item %>

<br>

<div>
  <%= link_to "Back to outfit items", outfit_items_path %>
</div>

app/views/outfit_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @outfit_item %>

<img class="img-thumbnail" style="width: 200px; height: 150px;" src="<%= @outfit_item.item.photo_url %>">

<div>
  <%= link_to "Edit this outfit item", edit_outfit_item_path(@outfit_item) %> |
  <%= link_to "Back to outfit items", outfit_items_path %>

  <%= button_to "Destroy this outfit item", @outfit_item, method: :delete %>
</div>