config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :outfits
  resources :outfit_items
  resources :items
  
  root "outfits#landing"
  get "/contact", to: "contact#new", as: "new_contact"
  post "/contact", to: "contact#create"
end

app/models/outfit.rb
# == Schema Information
#
# Table name: outfits
#
#  id         :integer          not null, primary key
#  vibe       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  owner_id   :integer
#  name       :string
#
# Indexes
#
#  index_outfits_on_owner_id  (owner_id)
#
# Foreign Keys
#
#  owner_id  (owner_id => users.id)
#
class Outfit < ApplicationRecord
  belongs_to :user, foreign_key: :owner_id
  has_many :outfit_items
  has_many :items, through: :outfit_items
  accepts_nested_attributes_for :outfit_items
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :set_outfit, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: :landing
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    @outfits = current_user.outfits
  end

  def show
    @outfit = Outfit.includes(:items).find(params[:id])
    @items = @outfit.items
    Rails.logger.debug "Items: #{@items.inspect}"
  end

  def new
    @outfit = Outfit.new
  end

  def edit
  end

  def create
    # Remove outfit_items_attributes from outfit_params
    @outfit = current_user.outfits.new(outfit_params.except(:outfit_items_attributes))
    
    items_params = params[:outfit][:outfit_items_attributes].map { |item| item[:item_id] }
  
    # this is so that I can make sure data isn't producing twice
    Rails.logger.debug "items_params: #{items_params}"
    
    items_params.each do |item_id|
      next unless current_user.items.find_by(id: item_id)
  
      @outfit.outfit_items.build(item_id: item_id)
    end
  
    respond_to do |format|
      if @outfit.save
        format.html { redirect_to outfit_url(@outfit), notice: "Outfit was successfully created." }
        format.json { render :show, status: :created, location: @outfit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @outfit.update(outfit_params)
        format.html { redirect_to outfit_url(@outfit), notice: "Outfit was successfully updated." }
        format.json { render :show, status: :ok, location: @outfit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @outfit.destroy

    respond_to do |format|
      format.html { redirect_to outfits_url, notice: "Outfit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def landing
  end
  
  private
  def set_outfit
    @outfit = current_user.outfits.find(params[:id])
  end

  def outfit_params
    params.require(:outfit).permit(:image, :vibe, :name)
    # params.require(:outfit).permit(:image, :vibe, :name, outfit_items_attributes: [:item_id])
  end

  def user_not_authorized
    flash[:alert] = "Uh oh! You are not authorized to do this."
    redirect_to(request.referer || root_path)
  end
end

app/views/outfits/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <%= form_with(model: @outfit) do |form| %>
            <% if @outfit.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(@outfit.errors.count, "error") %> prohibited this outfit from being saved:</h2>

                <ul>
                  <% @outfit.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div>
              <h5>What should be included in this outfit?</h5>
              <p><%= form.label :outfit_items %></p>
              <% current_user.items.each do |item| %>
                <%= check_box_tag 'outfit[outfit_items_attributes][]item_id', item.id, @outfit.items.include?(item) %>
                <%= item.details %>
              <% end %>
            </div>

            <div>
              <h5>What's the vibe of this outfit? This could even be an inspo photo:</h5>
              <small>This should be a URL</small>
              <p><%= form.label :vibe %></p>
              <%= form.text_field :vibe %>
            </div>

            <div class="mt-3">
              <h5>Let's add a name to this outfit:</h5>
              <small>This should be a description of the outfit or even the name of the event</small>
              <p><%= form.label :name %></p>
              <%= form.text_field :name %>
            </div>

            <div class="p-3">
              <%= form.submit class: "btn btn-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/outfits/_outfit.html.erb
<div id="<%= dom_id outfit %>">
  <p>
    <strong>Owner:</strong>
    <%= outfit.owner_id %>
  </p>

</div>

app/views/outfits/edit.html.erb
<h1>Editing outfit</h1>

<%= render "form", outfit: @outfit %>

<br>

<div>
  <%= link_to "Show this outfit", @outfit %> |
  <%= link_to "Back to outfits", outfits_path %>
</div>

app/views/outfits/index.html.erb
<div class="grid text-center">
  <div class="col-4"></div>
  <div class="col-4 mx-auto"> 
  <%# clean up indentation %>
    <%= link_to "New outfit", new_outfit_path, class: "btn btn-outline-light" %>
    <% if @outfits.any? %>
      <% @outfits.each do |outfit| %>
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
              <% if outfit.items.present? %>
                <% first_item = outfit.items.first %>
                  <img src="<%= outfit.vibe %>" class="img-fluid rounded-start" alt="This is the vibe of the outfit">
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title"><%= outfit.name %></h5>
                    <p class="card-text"><small class="text-body-secondary">Last updated <%= time_ago_in_words(outfit.updated_at) %> <%= link_to "Show this outfit", outfit %></small></p>
                  </div>
                <% else %>
                  <div class="card-body">
                      <p class="card-text">No items in this outfit</p>
                      <%= link_to "Show this outfit", outfit %>
                  </div>
                <% end %>
              </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>Uh oh, it looks like you haven't created anything yet!</p>
    <% end %>
  </div>
  <div class="col-4"></div>
</div>

app/views/outfits/landing.html.erb
<div class="container text-center">
  <div id="carouselExample" class="carousel slide mx-auto">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://i.imgur.com/YYpWImr.png" class="d-block w-75 mx-auto" alt="Welcome">
      </div>
      <div class="carousel-item">
        <img src="https://i.imgur.com/tgpQVxu.png" class="d-block w-75 mx-auto" alt="to">
      </div>
      <div class="carousel-item">
        <img src="https://i.imgur.com/5ZiIE81.png" class="d-block w-75 mx-auto" alt="UPick">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="text-center">
  <h4>Love the idea of getting ready but absolutely hate getting to the part where you have to get dressed?</h4>
</div>

<div class="text-center">
  <br>
  <h4>
    This is made for people who never can decide what to wear next, hate outfit repeating and aren't afraid of being in the spotlight.
    <p>Let's get you set up so U can Pick</p>
  </h4>
</div>

<div class="text-center">
  <div class="buttons-container d-grid gap-2 d-md-block">
    <% unless user_signed_in? %>
      <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-light' %>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-info' %>
    <% end %>
  </div>
</div>

app/views/outfits/new.html.erb
<h1>New outfit</h1>

<%= render "form", outfit: @outfit %>

<br>

<div>
  <%= link_to "Back to outfits", outfits_path %>
</div>

app/views/outfits/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <p style="color: green"><%= notice %></p>

      <h1 class="text-center">Outfit Details</h1>

      <h3 class="text-center">Name: <%= @outfit.name %> </h3>
      <p class="text-center"><strong>Date Made:</strong> <%= @outfit.created_at %></p>
      <h4 class="text-center">Vibe for this outfit: </h4>
      <img class="img-thumbnail mx-auto d-block" style="height: 350px; width: 350px;" alt="Outfit Image" src="<%= @outfit.vibe %>">
      <p class="text-center"><strong>Owner:</strong> <%= @outfit.user.email %></p>

      <ul class="text-center">
        <h2>Items in Outfit:</h2>

        <% if @outfit.items.any? %>
          <ul>
            <% @outfit.items.each do |item| %>
              <li>
                <%= item.details %>
                <br>
                Color: <%= item.color_hex %>
                <br>
                <img class="img-thumbnail mx-auto d-block" style="width: 200px; height: 150px;" src="<%= item.photo_url %>">
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>No items in this outfit</p>
        <% end %>
      </ul>

      <%= link_to 'Back', outfits_path, class: "btn btn-outline-light" %>

      <div class="text-center">
        <%= link_to "Edit this outfit", edit_outfit_path(@outfit), class: "btn btn-outline-light" %>
        <%= link_to "Back to outfits", outfits_path, class: "btn btn-outline-light" %>
        <%= button_to "Destroy this outfit", @outfit, method: :delete, class: "btn btn-outline-light" %>
      </div>
    </div>
  </div>
</div>