config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :outfits
  resources :outfit_items
  resources :items
  
  root "outfits#landing"
  get "/contact", to: "contact#new", as: "new_contact"
  post "/contact", to: "contact#create"
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  color_hex  :string
#  details    :string
#  photo_url  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  owner_id   :integer
#
# Indexes
#
#  index_items_on_owner_id  (owner_id)
#
# Foreign Keys
#
#  owner_id  (owner_id => users.id)
#
class Item < ApplicationRecord
  mount_uploader :photo_url, PhotoUrlUploader
  belongs_to :user, foreign_key: :owner_id
  has_many :outfit_items
  has_many :outfits, through: :outfit_items
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    @items = current_user.items
    @item = current_user.items.new
  end

  def show
    @item = Item.find(params[:id])
    authorize @item
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = current_user.items.new(item_params)
    authorize @item

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_item
      @item = current_user.items.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:photo_url, :color_hex, :details)
    end
    
    def user_not_authorized
      flash[:alert] = "Uh oh! You are not authorized to do this."
      redirect_to(request.referer || root_path)
    end
end

app/views/items/_form.html.erb
<%# remove unused code%>
<!--<div style="display: flex; justify-content: center; align-items: center; ">
  <%= form_with(model: item) do |form| %>
    <% if item.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
          <% item.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :photo_url, class: 'form-label' %>
      <%= form.file_field :photo_url, class: 'form-control' %>
    </div>

    <div>
      <h5>Cool! Let's add the color hex. Not sure? That's okay just put the color of the item! </h5>
      <%= form.label :color_hex, style: "display: block" %>
      <%= form.text_field :color_hex %>
    </div>

    <div>
      <h5>Let's name this item, a short descriuption of what it is: </h5>
      <%= form.label :details, style: "display: block" %>
      <%= form.text_field :details %>
    </div>

    <div>
      <%= form.submit class: "btn btn-outline-light" %>
    </div>
  <% end %>
</div>
-->
<div class="d-flex justify-content-center align-items-center">
  <div class="card" style="width: 30rem;">
    <div class="card-body">
      <h1 class="card-title fs-5 text-center">New Item</h1>

      <%= form_with(model: item, class: 'text-center') do |form| %>
        <% if item.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
            <ul>
              <% item.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <p><h5>Upload a photo of your item:</h5></p>
          <%= form.file_field :photo_url, class: 'form-control' %>
        </div>

        <div>
          <p><h5>What color is your item? </h5></p>
          <%= form.text_field :color_hex, class: 'form-control' %>
        </div>

        <div>
          <p><h5>Let's name this item, a short description of what it is: </h5></p>
          <%= form.text_field :details, class: 'form-control' %>
        </div>

        <div class="mt-3">
          <%= form.submit class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <div class="d-flex justify-content-center align-items-center">
    <div class="card" style="width: 30rem;">
      <div class="card-body text-center">
        <h1 class="card-title fs-5">Item Details</h1>

        <p>
          <h3>
          <strong>Name:</strong>
          <%= item.details %>
          </h3>
        </p>

        <p>
          <strong>Photo:</strong>
        </p>
          <img class="img-thumbnail" src="<%= item.photo_url %>">

        <p>
          <h3>
          <strong>Color:</strong>
          <%= item.color_hex %>
          </h3>
        </p>

        <p>
          <strong>Owner:</strong>
          <%= item.user.email %>
        </p>
      </div>
    </div>
  </div>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#newItemModal">New item</button>
<p style="color: green"><%= notice %></p>
<div class="modal fade" id="newItemModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Item</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <!-- your form goes here -->
        <%= form_with(model: @item) do |form| %>
          <% if @item.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
              <ul>
                <% @item.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="mb-3">
            <p>
              <h5 class="text-dark">Upload a photo of your item:</h5>
            </p>
            <%= form.file_field :photo_url, class: 'form-control' %>
          </div>

          <div>
            <p>
              <h5 class="text-dark">What color is your item? </h5>
            </p>
            <%= form.text_field :color_hex, class: 'form-control' %>
          </div>

          <div>
            <p>
              <h5 class="text-dark">Let's name this item, a short description of what it is: </h5>
            </p>
            <%= form.text_field :details, class: 'form-control' %>
          </div>

          <div class="mt-3">
            <%= form.submit class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if @items.any? %>
  <div class="row row-cols-1 row-cols-md-3 g-4" id="outfit_items">
    <% @items.each do |item| %>
      <div class="col">
        <div class="card">
          <% if item.present? %>
            <img src="<%= item.photo_url %>" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title"><%= item.details %></h5>
              <%= link_to "Show this outfit item", item %>
            </div>
          <% else %>
            <div class="card-body">
              <p class="card-text"></p>
              <%= link_to "Show this outfit item", item %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>Uh oh, it looks like you haven't created anything yet!</p>
<% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item), class: "btn btn-outline-light" %>
  <%= link_to "Back to items", items_path, class: "btn btn-outline-light" %>

  <%= button_to "Destroy this item", @item, method: :delete, class: "btn btn-outline-light" %>
</div>