config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :outfits
  resources :outfit_items
  resources :items
  
  root "outfits#landing"
  get "/contact", to: "contact#new", as: "new_contact"
  post "/contact", to: "contact#create"
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id          :integer          not null, primary key
#  description :text
#  email       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Contact < ApplicationRecord
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  class ContactController < ApplicationController
    def new
      @contact = Contact.new
    end
  
    def create
      @contact = Contact.new(contact_params)
      if @contact.save
        ContactMailer.contact_email(@contact).deliver_now
        redirect_to root_path, notice: "Message sent successfully!"
      else
        render :new
      end
    end
  
    private
  
    def contact_params
      params.require(:contact).permit(:email, :description)
    end
  end
end

app/views/contact/new.html.erb
<h1>Contact Me</h1>

<% if notice %>
  <p style="color: green;"><%= notice %></p>
<% end %>

<%= form_with(model: @contact, url: contact_path, method: :post) do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit "Send Message" %>
  </div>
<% end %>